name: Deploy vue.js to aws s3

on:
  push:
    branches: [master, dev, ci]

jobs:
  delpoy_to_s3:
    runs-on: ubuntu-latest

    env:
      PHASE: "${{ github.ref_name == 'master' && 'prod' || github.ref_name }}"
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_S3_REGION }}

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache node modules
        if: ${{ github.ref_name != 'ci' }}
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        if: ${{ github.ref_name != 'ci' }}
        run: |
          npm ci

      - name: Build
        if: ${{ github.ref_name != 'ci' }}
        run: |
          npm run build -- --mode ${{ env.PHASE }}

      - name: Deploy
        if: ${{ github.ref_name != 'ci' }}
        run: |
          aws s3 sync --delete --quiet dist s3://${{ secrets.AWS_S3_NAME }}/${{ env.PHASE }}

      - name: Invalidate CloudFront cache
        if: ${{ env.PHASE != 'prod' && github.ref_name != 'ci'}}
        run: |
          if [ $PHASE == "dev" ]; then
            CF_DIST=${{ secrets.AWS_CF_DIST_DEV }}
          elif [ $PHASE == "staging" ]; then
            echo "1234"
          fi

          aws cloudfront create-invalidation --distribution-id $CF_DIST --paths "/*"

  create_pr:
    runs-on: ubuntu-latest
    needs: [delpoy_to_s3]
    if: ${{ github.ref_name != 'master' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Check var
        env:
          TEST: ${{ toJson(github) }}
        run: echo $TEST

      - name: Create pr

        run: |
          PR_URL=`
            gh pr create \
              --title '${{ github.event.head_commit.message }}' \
              --body 'Created by DevOps bot.' \
              --head '${{ github.ref_name }}' \
              --base 'master'`
          echo '::set-output name=PR_URL::$PR_URL'
        id: create_pr

      - name: Auto merge
        run: |
          TITLE=`gh pr view ${{ steps.create_pr.outputs.PR_URL }} --json title | jq ".title"`
          gh pr merge --auto --merge --title $TITLE
