name: Deploy vue.js to aws s3

on:
  push:
    branches:
      - "master"

jobs:
  delpoy_to_s3:
    runs-on: ubuntu-latest
    env:
      CHOSHSH: choshsh-test
    steps:
      - uses: actions/checkout@v2
      
      - name: Test
        run: echo ${{ env.CHOSHSH }} 

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install NPM Dependencies
        if: ${{ github.ref_name == 'master' }}
        run: yarn install --frozen-lockfile

      - name: Build vue.js
        run: yarn build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync --delete --quiet \
            --region ${{ secrets.AWS_S3_REGION }} \
            dist s3://${{ secrets.AWS_S3_NAME }}
